#!/bin/bash
if [ -f /usr/local/bin/micro ]; then
  micro -v && exit
fi
echo "Downloading micro..."
rm -f /tmp/micro.tar.gz
curl -sSL https://github.com/micro/micro/releases/download/v1.18.0/micro-v1.18.0-darwin-amd64.tar.gz -o /tmp/micro.tar.gz
tar zxf /tmp/micro.tar.gz -C /tmp
mv /tmp/micro /usr/local/bin/
rm -f /tmp/micro.tar.gz
micro -v
